services:
  - type: web
    name: tcc-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: cd backend && npm install && npm run build:prod
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tcc-database
          property: connectionString
      - key: FRONTEND_URL
        value: https://tcc-frontend.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password

databases:
  - name: tcc-database
    plan: starter
    region: oregon
